al5d_arm_position_controller1:
  type: "effort_controllers/JointPositionController"
  joint: base_rotate
  pid: {p: 50.0, d: 10.0, i_clamp: 1.0}
  antiwindup: True
al5d_arm_position_controller2:
  type: "effort_controllers/JointPositionController"
  joint: shoulder_tilt
  pid: {p: 50.0, d: 10.0, i: 100.0, i_clamp: 1.0}
  antiwindup: True
al5d_arm_position_controller3:
  type: "effort_controllers/JointPositionController"
  joint: elbow_tilt
  pid: {p: 50.0, d: 10.0, i: 100.0, i_clamp: 1.0}
  antiwindup: True
al5d_arm_position_controller4:
  type: "effort_controllers/JointPositionController"
  joint: wrist_tilt
  pid: {p: 50.0, d: 10.0, i: 0.01, i_clamp: 1.0}
  antiwindup: True
al5d_arm_position_controller5:
  type: "effort_controllers/JointPositionController"
  joint: wrist_rotate
  pid: {p: 50.0, d: 10.0, i: 0.005, i_clamp: 1.0}
  antiwindup: True
al5d_gripper_controller1:
  type: "effort_controllers/JointPositionController"
  joint: open_gripperright
  pid: {p: 50.0, d: 10.0, i: 0}
  antiwindup: True
al5d_gripper_controller2:
  type: "effort_controllers/JointPositionController"
  joint: open_gripperleft
  pid: {p: 50.0, d: 10.0, i: 0}
  antiwindup: True
al5d_lidar_controller:
  type: "effort_controllers/JointPositionController"
  joint: lidar_rotate
  pid: {p: 50.0, d: 1.0, i: 0.005, i_clamp: 1.0}
  antiwindup: True
